const { chromium } = require('playwright');
(async()=>{
 const browser = await chromium.launch({headless:true});
 const publicPage = await browser.newPage();
 const editorPage = await browser.newPage();
 const publicHydration=[]; const editorHydration=[];
 const cap = arr => msg => { const t=`${msg.type()}: ${msg.text()}`; if(/hydration|did not match|Hydration/i.test(t)) arr.push(t); };
 publicPage.on('console', cap(publicHydration));
 editorPage.on('console', cap(editorHydration));
 await publicPage.goto('http://localhost:3000/', {waitUntil:'networkidle'});
 await editorPage.goto('http://localhost:3000/editor', {waitUntil:'networkidle'});
 const publicText = await publicPage.locator('body').innerText();
 const hasWild = publicText.includes('Wild at Heart');
 const hasNoLiveDivider = !(publicText.includes('section-divider-band-live') || publicText.includes('section-divider-live-contact'));
 const streamingItems = await publicPage.locator('[data-link-item="true"][data-editor-node-id^="live-streaming-"]').count();
 const socialItems = await publicPage.locator('[data-link-item="true"][data-editor-node-id^="live-social-"]').count();
 const liveGroup = editorPage.locator('[data-editor-node-id="live-stream-platforms-group"]');
 await liveGroup.scrollIntoViewIfNeeded();
 await liveGroup.click({force:true});
 await editorPage.waitForTimeout(700);
 const platformLinksVisible = await editorPage.locator('text=Platform Links').count();
 const spotifyField = await editorPage.locator('label:text("Spotify")').count();
 const upcomingTitle = editorPage.locator('[data-editor-node-id="live-upcoming-title"]');
 await upcomingTitle.click({force:true});
 await editorPage.waitForTimeout(700);
 const addVisible = await editorPage.getByRole('button', {name:'Add Concert'}).count();
 const deleteVisible = await editorPage.getByRole('button', {name:'X'}).count();
 const concertButton = editorPage.getByRole('button', {name:/Wild at Heart|Berlin|Concert/}).nth(1);
 const concertButtonText = await concertButton.textContent().catch(()=>null);
 if (concertButtonText) await concertButton.click();
 await editorPage.waitForTimeout(500);
 const concertEditorVisible = await editorPage.locator('text=Concert Editor').count();
 console.log(JSON.stringify({hasWild, hasNoLiveDivider, streamingItems, socialItems, platformLinksVisible, spotifyField, addVisible, deleteVisible, concertButtonText, concertEditorVisible, publicHydration, editorHydration}, null, 2));
 await browser.close();
})();
